# Generated by Django 5.2 on 2025-05-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpal_adoption', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='adopter',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='experience',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='homeType',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
