# Generated by Django 5.2 on 2025-05-30 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpal_adoption', '0002_remove_adoptionapplication_adopter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petpal_adoption.pet'),
        ),
    ]
